name: convert Jupyter notebooks to R scripts and R Markdown files

on:
  push:
    paths:
      - "**/*.ipynb"
      - ".github/workflows/**"
  workflow_dispatch:

jobs:
  convert:
    name: convert Jupyter notebooks to R scripts and R Markdown files
    runs-on: ubuntu-latest

    steps:
      - name: check out repository
        uses: actions/checkout@v3

      - name: set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      
      - name: install ipyrmd package
        run : pip install ipyrmd
      
      - name: run conversion to R scripts
        run: |
          mkdir -p scripts
          for f in *.ipynb; do ipyrmd --to R -o scripts/${f%.*}.R $f; done

      - name: run conversion to R Markdown
        run: |
          mkdir -p scripts
          for f in *.ipynb; do ipyrmd --to Rmd -o scripts/${f%.*}.md $f; done

      - name: Git add & commit
        uses: EndBug/add-and-commit@v9
        with:
          add: "."
          default_author: github_actor
          message: "update R scripts"
          push: true
